### ISSUE TITLE
"code": 3, "message": "execution reverted: Crowdsale: weiAmount is 0"

### ISSUE THREAD

**Issue by Freda46** [FreezyEx/PreSale-Contract#1]
hi, how to fix this?
Internal JSON-RPC error. { "code": 3, "message": "execution reverted: Crowdsale: weiAmount is 0", "data": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001943726f776473616c653a20776569416d6f756e74206973203000000000000000" }

**Comment by FreezyEx** [comment]
Make sure you have set the rate

**Comment by Freda46** [comment]
I have 300,000 Coin with 18 Decimals and I set rate for 1000, is this wrong?
please help me how to set rate if I need 1 BNB = 100 Coin.
Thanks
