### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by taneemtur** [FreezyEx/PreSale-Contract#14]
Hi Freezy, I have cloned your code few times before and it worked fine. Today I am trying to use the old code and also this new one but every time the transaction gets failed.

https://testnet.bscscan.com/address/0xdcb32e59008079a2fcb015bbb8bedf1c7eef6c8d
https://testnet.bscscan.com/address/0x0b03929aacf9bf963d46b06adf858cfcf0d46fc9
https://testnet.bscscan.com/address/0xb790f58fcafadbb131a580fc5383a0b9d902cd19

**Comment by FreezyEx** [comment]
Please remember to set gas limit to at least 300k

Il giorno mar 7 dic 2021 alle ore 08:57 Taneem UR Rehman <
***@***.***> ha scritto:

**Comment by taneemtur** [comment]
It works fine again. Now I believe more in "if it works don't touch it" HAHA
Nothing changed including gas limit. Thanks anyways.

https://testnet.bscscan.com/address/0x95205bea9d2798197c53c4c8f6413e0e43c4eb0f
