### ISSUE TITLE
execution reverted: Crowdsale: weiAmount is 0

### ISSUE THREAD

**Issue by Freda46** [FreezyEx/PreSale-Contract#3]
Hi, I have followed the instructions on this site https://www.notion.so/Pre-Sale-Contract-78bbe4f84363424dbc7cd1388e78121c,
but I have this error
Internal JSON-RPC error. { "code": 3, "message": "execution reverted: Crowdsale: weiAmount is 0", "data":
even though I have filled in the rate as on your site

**Comment by FreezyEx** [comment]
You have done something wrong. Please check

**Comment by Freda46** [comment]
do you have a deploy example in bsc main or bsc testnet?

**Comment by YorgunDemokrat** [comment]
I can't call startICO? Can you explain for me?

**Comment by FreezyEx** [comment]
Probably you didn't send tokens to presale contract

**Comment by YorgunDemokrat** [comment]
No, I will send the tokens but I can't ETH to my contract. I can't press the confirm button.

**Comment by FreezyEx** [comment]
if you don't start presale of course

**Comment by YorgunDemokrat** [comment]
How can I start my pre-sale? You said earlier that I needed to send the tokens to start the pre-sale. I did this but it didn't work. I'm new to this stuff and trying to learn. Can you give more detailed information?

**Comment by Freda46** [comment]
not fix
