### ISSUE TITLE
Fail with error 'availableTokens should be > 0 and <= totalSupply'

### ISSUE THREAD

**Issue by letmein2** [FreezyEx/PreSale-Contract#4]
Hey Freezy. I very much appreciate the help so far. I've got the presale contract deployed but when i go to start the ICO i get the following transaction error - Fail with error 'availableTokens should be > 0 and <= totalSupply' .

I set the following settings on deploy for the rate (5 Trill per bnb) , address, token address, etc.
5000000000000,0x5B9cED86ecDc2d859D8126A08E429f07d9B15409,0xa43c607c836c250f851a50c385d4d906ea829c66

On startICO I set the following

0 | endDate | uint256 | 1624238552 - (Jun 20 2021 20:22:32)

1 | _minPurchase | uint256 | 100000000000000000 - (equal to .1 ETH.BNB)

Not sure why it's giving me the availableTokens error as supply is 1 quadtrill.  I've looked this up and down and i see no reason that they contract is seeing my token with zero tokens available. I've read through the code and I know it's happening in the code below but i see no reason for the error.

uint _availableTokens = _token.balanceOf(address(this));
require(_availableTokens > 0 && _availableTokens <= _token.totalSupply(), 'availableTokens should be > 0 and <= totalSupply')

Thanks

Mike

**Comment by letmein2** [comment]
Never Mind. I've pulled my head out of my rear and know what I didn't do. 
Thanks for this ICO contract. Very Nice.

**Comment by Aarsh3** [comment]
what did you do?
